# Generated by Django 4.2.4 on 2023-08-31 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grossesse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('intensite', models.CharField(max_length=2)),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('grossesse_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grossesse.grossesse')),
            ],
        ),
    ]
